_target_: training.dlwp.model.models.unet3plus.Unet3plusDecoder
_recursive_: false
n_channels:
  - 256
  - 128
  - 64
convolutions_per_depth: 2
kernel_size: 3
dilations:
  - 4
  - 2
  - 1
upsampling_type: interpolate
upsampling: 2
activation:
  _target_: training.dlwp.model.modules.activations.CappedGELU
  cap_value: 10.
