defaults:
  - /model/modules/blocks@conv_block: basic_conv_block
  - /model/modules/blocks@up_sampling_block: transposed_conv_upsample
  - /model/modules/blocks@recurrent_block: null
  - /model/modules/blocks@output_layer: output_layer

_target_: training.dlwp.model.models.unet.UNetDecoder
_recursive_: false
n_channels:
  - 256
  - 128
  - 64
n_layers:
  - 1
  - 2
  - 2
dilations:
  - 1
  - 1
  - 1
