defaults:
  - _self_
  - analysis: acc
  - evaluator: hpx
  - paths: default
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

model_name: null
transfer_das: False
rescale_das: False
eval_variable: z500
poolsize: 30
verbose: True

hydra:
  verbose: False
  output_subdir: null  
