defaults:
  - remap_config: cs64

_target_: evaluation.evaluators.EvaluatorCS
forecast_path: null  # Leave empty; will be overridden
verification_path: ${paths.verification_ll}
eval_variable: ${eval_variable}
unit_conversion: null
on_latlon: ${analysis.on_latlon}
times: 
poolsize: ${poolsize}
verbose: ${verbose}
