defaults:
  - remap_config: hpx32

_target_: evaluation.evaluators.EvaluatorHPX
forecast_path: null  # Leave empty; will be overridden
verification_path: ${paths.verification_ll}
eval_variable: ${eval_variable}
unit_conversion:
on_latlon: ${analysis.on_latlon}
times: null
poolsize: ${poolsize}
verbose: ${verbose}
