_target_: evaluation.evaluators.EvaluatorLL
forecast_path: null  # Leave empty; will be overridden
verification_path: ${paths.verification_ll}
eval_variable: ${eval_variable}
unit_conversion:
on_latlon: True
times: null
poolsize: ${poolsize}
verbose: ${verbose}
