defaults:
  - modules/encoder@atmos_encoder: hpx_unet3plus_encoder
  - modules/decoder@atmos_decoder: hpx_unet3plus_decoder
  - modules/encoder@ocean_encoder: hpx_unet3plus_encoder
  - modules/decoder@ocean_decoder: hpx_unet3plus_decoder

_target_: training.dlwp.model.models.double_unet.CoupledUnet
_recursive_: false
input_time_dim: ${data.input_time_dim}
output_time_dim: ${data.output_time_dim}
nside: ${data.nside}
presteps: 0

# Parameters automatically overridden in train code
# input_channels
# output_channels
# n_constants
# decoder_input_channels
input_channels: 1
output_channels: 1
n_constants: 1
decoder_input_channels: 1
