defaults:
  - modules/encoder@encoder: hpx_unet3plus_encoder
  - modules/decoder@decoder: hpx_unet3plus_decoder

_target_: training.dlwp.model.models.unet3plus.HEALPixUNet3Plus
_recursive_: false
input_time_dim: ${data.input_time_dim}
output_time_dim: ${data.output_time_dim}
nside: ${data.nside}

# Parameters automatically overridden in train code
# input_channels
# output_channels
# n_constants
# decoder_input_channels
input_channels: 1
output_channels: 1
n_constants: 1
decoder_input_channels: 1
